apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: skillpath-data-pvc
  namespace: skillpath
  labels:
    app: skillpath
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
